image: quay.io/vmoteam/ci-node:v12-gitops

definitions:
  services:
    docker:
      memory: 1024
  caches:
    nodecaching: ./node_modules
  steps:
    - step: &build-deploy
        name: Build & Deploy to Test
        deployment: Test
        caches:
          - nodecaching
        script:
          - pipe: atlassian/aws-ecr-push-image:1.4.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

pipelines:
  branches:
    # Run testing
    feature/build-docker:
      - step:
          <<: *build-deploy
          name: Test
          size: 2x
          caches:
            - nodecaching
            - docker
          script:
            # ENV build in
            - APPLICATION=vin21083
            - NAMEAPP=rain
            - ENV=test
            - BRANCH=feature/build-docker
            - VERSION=$ENV-$(git rev-parse --short HEAD)
            - IMAGE_FIX=$DOCKER_REGISTRY_HOST/$APPLICATION:$NAMEAPP-$ENV
            - IMAGE_BACKUP=$DOCKER_REGISTRY_HOST/$APPLICATION:$NAMEAPP-$VERSION

            # install & build
            - npm install

            # build docker application
            - docker build -t $IMAGE_FIX -f Dockerfile .
            - docker tag $IMAGE_FIX $IMAGE_BACKUP

            - echo $AWS_ACCESS_KEY_ID
            - echo $AWS_SECRET_ACCESS_KEY

            # login aws ecr
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY_HOST
            - docker push $IMAGE_BACKUP

            # Deployment
            - helm version
            - mkdir -p ~/.kube
            - echo -n $CONFIG | base64 -d > ~/.kube/config
            - chmod 400 ~/.kube/config
            - cd helm/$NAMEAPP
            # Deploy to K8s test
            - helm upgrade -i $NAMEAPP ./ --set image.tag=$NAMEAPP-$ENV-$CI_COMMIT_SHORT_SHA -f test.values.yaml -n test

          services:
            - docker

