image: quay.io/vmoteam/ci-node:v12-gitops

definitions:
  services:
    docker:
      memory: 1024
  caches:
    nodecaching: ./node_modules

pipelines:
  branches:
    # Run testing
    feature/build-docker:
      - step:
          name: Test
          size: 2x
          caches:
            - nodecaching
            - docker
          script:
            # ENV build in
            - APPLICATION=vin21083
            - NAMEAPP=green-rain
            - ENV=test
            - BRANCH=feature/build-docker
            - VERSION=$ENV-$(git rev-parse --short HEAD)
            - IMAGE_FIX=$DOCKER_REGISTRY_HOST/$APPLICATION:$NAMEAPP-$ENV
            - IMAGE_BACKUP=$DOCKER_REGISTRY_HOST/$APPLICATION:$NAMEAPP-$VERSION

            # install & build
            # - npm install

            # build docker application
            - docker build -t $IMAGE_FIX -f Dockerfile .
            - docker tag $IMAGE_FIX $IMAGE_BACKUP

            # login aws ecr
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY_HOST
            - docker push $IMAGE_BACKUP

          services:
            - docker
      - step:
          image: alpine/helm:latest
          size: 2x
          caches:
            - nodecaching
            - docker
          script:
            - APPLICATION=vin21083
            - NAMEAPP=green-rain
            - ENV=test
            - BRANCH=feature/build-docker
            - VERSION=$ENV-$(git rev-parse --short HEAD)
            - IMAGE_FIX=$DOCKER_REGISTRY_HOST/$APPLICATION:$NAMEAPP-$ENV
            - IMAGE_BACKUP=$DOCKER_REGISTRY_HOST/$APPLICATION:$NAMEAPP-$VERSION

            - helm version
            - mkdir -p ~/.kube
            - echo -n $CONFIG | base64 -d > ~/.kube/config
            - chmod 400 ~/.kube/config
            - cd helm/$NAMEAPP
            # Deploy to K8s test
            - helm upgrade -i $NAMEAPP ./ --set image.tag=$NAMEAPP-$VERSION -f test.values.yaml -n test

          services:
            - docker

