pipeline {

    environment {
        registry = "ductn4/green-rain"
        registryCredential = "dockerhub_id"
        dockerImage = ''
    }

    agent any

    stages {

        // Clone git repo
        stage('clone') {
            steps {
                git 'https://github.com/ductnn/Green-Rain.git'
            }
        }

        // Build Image
        stage('Build Image') {
            steps {
                script {
                    dockerImage = docker.build registry + ":latest"
                }
            }
        }

        // Deploy Image
        stage('Deploy Image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }

        // Remove image
        stage('Remove') {
            steps {
                sh "docker rmi $registry:latest"
            }
        }
    }
}
