pipeline {

    environment {
        registry = "ductn4/green-rain"
        registryCredential = "dockerhub_id"
        dockerImage = ''
    }

    agent any

    stages {

        // Clone git repo
        stage('clone') {
            steps {
                git 'https://github.com/ductnn/Green-Rain.git'
            }
        }

        // Build Image
        stage('Build Image') {
            agent {
                	docker {
                        	reuseNode true
                        	image 'ductn4/green-rain:1.1'            // Docker image for testing environment
                        	args '-p 3000:3000 --privileged -v /var/run/docker.sock:/var/run/docker.sock'
                	}
           	}
            steps {
                script {
                    dockerImage = docker.build registry + ":latest"
                }
            }
        }

        // Deploy Image
        stage('Deploy Image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }

        // Remove image
        stage('Remove') {
            steps {
                sh "docker rmi $registry:latest"
            }
        }
    }
}
